name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  buttons_tabbar: ^1.3.10
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  hexcolor: ^3.0.1
  provider: ^6.1.2
  water_drop_nav_bar: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
